# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install Flask

# Run the Flask application when the container launches
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
